### ISSUE TITLE
Design the protocol

### ISSUE THREAD

**Issue by mgrabovsky** [mgrabovsky/pv204-spring2020-project#2]
We need to design the protocol for a secure channel between the card and our host application. There are some hints in lecture 6 (_Secure Authentication & Authorization_).

It was also suggested we aim for an ECDH-based system with mutual authentication being performed during the initial shared key establishment. I think this can be achieved using [PAKE](https://en.m.wikipedia.org/wiki/Password-authenticated_key_agreement)-type protocol, such as [EKE](https://en.m.wikipedia.org/wiki/Encrypted_key_exchange) or [SPEKE](https://en.m.wikipedia.org/wiki/SPEKE). (More investigation is needed here.)

Generally, we need to ensure the following properties of the channel:
+ confidentiality of the data and PIN,
+ integrity of the transmitted data,
+ freshness of data and keys,
+ replay and MitM attacks prevention,
+ forward secrecy.

All the cryptography primitives used, messages transmitted and properties of the protocol will be documented.

**Comment by Nomit1993** [comment]
We can indeed use SPEKE.

**Comment by mgrabovsky** [comment]
This is kind of done. We just need to document the protocol we've implemented. Will also be useful for the final report. Moving this to #7.
